### ISSUE TITLE
Algorithms in java

### ISSUE THREAD

**Issue by anku580** [anku580/Java-Algorithms#1]
### Keep on adding new algorithms to this repository, so that a developer can easily access it here.

For starters, you can add simple algorithms like - anagram, prime number, remove duplicate elements etc.

Also, make sure to follow me [here](https://github.com/anku580), I will follow you back. We can have a long discussion to contribute in open source.

## If you want to learn on how to resolve merge conflicts, you can watch this [youtube video](https://youtu.be/Mrh_YmPqNU8)

**Comment by nimendrak** [comment]
I would like to contribute in this one!

**Comment by anku580** [comment]
@nimendrak sure, please go ahead.

**Comment by Nanocat7** [comment]
Me too
I would like to contribute in this one

**Comment by jayeshkumar09** [comment]
hey i am  new to this  i would like to contribute

**Comment by banerjee-suchismita** [comment]
Hey, I would like to contribute by implementing Longest Common Subsequence.

**Comment by ashitajain14** [comment]
Hey, I would like to contribute by implementing Merge Sort

**Comment by SagarGi** [comment]
Hey, I would also like to add algorithms

**Comment by Neuroxic** [comment]
Hey, i would like to add sone kind of sorting algorithm

**Comment by anku580** [comment]
Hey @JKjayeshkumar  @banerjee-suchismita @ashitajain14 @SagarGi and @Neuroxic . Please go ahead and add your valuable contributions.

**Comment by ANKITAKHAN** [comment]
Hey @anku580 , I would like to contribute to it all the sorting and searching algorithms in the most optimized way.

**Comment by anku580** [comment]
Hi @ANKITAKHAN Sure, you can contribute 💯

**Comment by brijeshsos66** [comment]
I would like to add Graph Traversal Algorithms i.e, BFS & DFS.

**Comment by anku580** [comment]
sure @brijeshsos66, please go ahead :+1:

**Comment by Gagan-Shenoy** [comment]
Hey can I work on Linked Lists : ) @anku580

**Comment by anku580** [comment]
Hi @Gagan-Shenoy sure, you can work on it 👍

**Comment by KeerthanaHK** [comment]
Hey, Can I work on this? I'm a beginner

**Comment by anku580** [comment]
@KeerthanaHK sure please, go ahead and start contributing.

**Comment by anamkhxn** [comment]
Hey, I'd like to add Topological Sort.

**Comment by anku580** [comment]
@anamkhxn, sure please go ahead

**Comment by Raksha25** [comment]
Hi @anamkhxn , I would like to contribute to this.

**Comment by anku580** [comment]
@Raksha25 Sure please go ahead 👍

**Comment by Vaibhav22-Dev** [comment]
I would like to contribute Kernighan's algo and Josephus algo of bit manipulation in optimized way , with your permission , i am waiting.

**Comment by anku580** [comment]
@Vaibhav22-Dev Sure please go ahead :+1:

**Comment by Anjali2001saxena** [comment]
I would like to contribute Balanced bracket using stack. I am waiting for your approval.

**Comment by anku580** [comment]
@Anjali2001saxena sure please go ahead.

**Comment by Anjali2001saxena** [comment]
I would also like to contribute jump search, if you approve that.

**Comment by anku580** [comment]
@Anjali2001saxena yes please go ahead :)

You are doing really well.

**Comment by Anjali2001saxena** [comment]
Thank you @anku580 :)
