### ISSUE TITLE
Update the README file

### ISSUE THREAD

**Issue by anku580** [anku580/Java-Algorithms#16]
### To Update the README file

The README file does not contain much information. So, you can work on updating the README file and add more information about the repository.

Please do reach out to me in [linkedin](https://www.linkedin.com/in/anku580/) to know more about the repository descrption.

**Comment by Cybertron-Avneesh** [comment]
Can i do this @anku580 ?

**Comment by frbio** [comment]
Hey, I can work on this. Can you Assign me?

**Comment by anku580** [comment]
Hi @Cybertron-Avneesh Sure, you can proceed.

**Comment by anku580** [comment]
Hey @frbio you can also start working on it.

**Comment by 23krishna** [comment]
Hii can I work on it?
Also can you tell me what to update on the file?

**Comment by anku580** [comment]
Hi @23krishna sure you can work on it. 

Since this repository is about the DS and Algorithms in Java, you can add the description of the repo and add some emojis. You can use some README templates to get more help.

Something like this - https://github.com/othneildrew/Best-README-Template
