### ISSUE TITLE
Add Java Algorithms

### ISSUE THREAD

**Issue by anku580** [anku580/Java-Algorithms#63]
You can include any algorithms written in java and raise the PR.

## If you want to learn on how to resolve merge conflicts, you can watch this [youtube video](https://youtu.be/Mrh_YmPqNU8)

**Comment by priya-pri** [comment]
Heyy ,Can you assign this to me .I would like to work on this

**Comment by anku580** [comment]
@priya-pri Sure please go ahead :)

**Comment by Procoder16** [comment]
@anku580 sir, I would like to work on this.

Can you please assign me this??

**Comment by Kartik987** [comment]
Hey @anku580. I would like to contribute.

**Comment by anku580** [comment]
Sure please go ahead

**Comment by Kartik987** [comment]
I have just created a PR regarding Exponential Search algorithm. Please check.

**Comment by priya-pri** [comment]
I have added stack program in java.Please review my PR

**Comment by Procoder16** [comment]
@anku580 sir, I have added the Huffman Coding Algorithm using java.

Hope that would be enough as per this repository.

Kindly review it and merge it to the main branch if it looks completely OK.
